version: '3.8'

services:
  bot:
    build: .
    container_name: music_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:passz@yandex-music:5432/music_uploader

  db:
    image: postgres:15-alpine
    container_name: music_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passz
      POSTGRES_DB: music_uploader
    volumes:
      - postgres_data:/var/lib/postgresql/data–∞
    ports:
      - "5432:5432"

volumes:
  postgres_data:
